version: '3'

services:
  postgres:
    build:
      context: ../shared/postgres
    image: starter-postgres:prod
    ports:
      - "5432:5432"
    networks:
      - prod
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    volumes:
      - postgres_data:/var/lib/postgresql/data
    container_name: starter_postgres

  chuut_back:
    image: starter-back:release
    container_name: chuut_back
    volumes:
      - ../.././:/code
    env_file:
      - ./back/.env
    environment:
        - FLASK_APP=main.py
    ports:
      - "5001:5001"
      - "9001:9001"
    restart: always
    networks:
      - prod

networks:
  prod:

volumes:
  postgres_data: